name: Copy Code for Version Tags

on:
  push:
    tags:
      - 'v*'  # Matches any tag starting with "v"

jobs:
  copy-code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check for release tag
        id: check_tag
        run: |
          echo "::set-output name=tag::$(echo ${GITHUB_REF#refs/tags/})"  # Extract tag from GITHUB_REF

      - name: Check if tag exists
        uses: gr2m/conditional-action@v2
        with:
          condition: startsWith(github.ref, 'refs/tags/')  
          fail-message: 'This action only runs for release tags.'
          jobs: 'copy-code'

      - name: Copy Code for Release Tag
        run: |
          version=${{ steps.check_tag.outputs.tag }}  # Get extracted tag
          mkdir -p src/$version  # Create directory using the tag name
          cp -r src/* src/$version/  # Copy files to the version directory
